-- 계정 생성
--create user donet identified by donet;
--grant create session,connect, resource, create view, create trigger, create table, create sequence,create procedure to donet;

-- =================================TABLE DROP문===========================================
DROP TABLE GOODS_CATEGORY ;
DROP TABLE FUNDING_CATEGORY;
DROP TABLE GOODS;
DROP TABLE GOODS_PURCHASE ;
DROP TABLE REQUIRED_CATEGORY ;
DROP TABLE GOODS_IMAGE;
DROP TABLE FUNDIONG_GOODS;
DROP TABLE FUNDIONG_SUPPORTER;
DROP TABLE FUNDING_IMAGE;
DROP TABLE FUNDING_REPLY;
DROP TABLE FUNDING_PROJECT;

-- ============================= SEQUENCE DROP문 ======================================== 
DROP SEQUENCE SEQ_FUNDING_PROJECT;
DROP SEQUENCE SEQ_GOODS;
DROP SEQUENCE SEQ_FUNDING_PROJECT;
DROP SEQUENCE FUNDING_CATEGORY;
DROP SEQUENCE GOODS_CATEGORY;

-- ============================= TRRIGER DROP문 ======================================== 

-- ============================= VIEW DROP문 ======================================== 



-- ============================= CREATE TABLE======================================== 
-- 18. 물품 카테고리
CREATE TABLE GOODS_CATEGORY	(
    GOODS_CATEGORY_NO NUMBER  NOT NULL,
    GOODS_CATEGORY_NAME VARCHAR2(30)  NOT NULL,
    CONSTRAINT PK_GOODS_CATEGORY PRIMARY KEY(GOODS_CATEGORY_NO)
);
COMMENT ON TABLE GOODS_CATEGORY  IS '물품 카테고리';
COMMENT ON COLUMN GOODS_CATEGORY.GOODS_CATEGORY_NO IS '물품 카테고리 번호';
COMMENT ON COLUMN GOODS_CATEGORY.GOODS_CATEGORY_NAME IS '물품 카테고리 이름';


-- 36.펀딩프로젝트 카테고리				
CREATE TABLE FUNDING_CATEGORY (
    FUNDING_CATEGORY_NO NUMBER NOT NULL,
    FUNDING_CATEGORY_NAME VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_FUNDING_CATEGORY_NO PRIMARY KEY(FUNDING_CATEGORY_NO)
);
COMMENT ON TABLE FUNDING_CATEGORY IS '펀딩프로젝트 카테고리';
COMMENT ON COLUMN FUNDING_CATEGORY.FUNDING_CATEGORY_NO IS '펀딩프로젝트 카테고리 번호';
COMMENT ON COLUMN FUNDING_CATEGORY.FUNDING_CATEGORY_NAME IS '펀딩 카테고리 이름';




-- 6_구호물품 
CREATE TABLE GOODS(
    GOODS_NO NUMBER NOT NULL,
    GOODS_NAME VARCHAR2(50) NOT NULL,
    GOODS_PRICE NUMBER NOT NULL,
    GOODS_CATEOGRY_NO NUMBER NOT NULL,
    CONTENTS VARCHAR2(5000) NOT NULL,
    THUMBNAIL_ORIGIN_NAME VARCHAR2(1000),
    THUMBNAIL_CHANGE_NAME VARCHAR2(1000),
    HITS NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_GOODS PRIMARY KEY(GOODS_NO)
);

COMMENT ON TABLE GOODS IS '구호물품';
COMMENT ON COLUMN GOODS.GOODS_NO IS '구호물품 번호';
COMMENT ON COLUMN GOODS.GOODS_NAME IS '구호물품명';
COMMENT ON COLUMN GOODS.GOODS_PRICE IS '가격';
COMMENT ON COLUMN GOODS.GOODS_CATEOGRY_NO IS '물품카테고리번호';
COMMENT ON COLUMN GOODS.CONTENTS IS '구호 물품 내용';
COMMENT ON COLUMN GOODS.THUMBNAIL_ORIGIN_NAME IS '구호물품 대표사진 원래 이름';
COMMENT ON COLUMN GOODS.THUMBNAIL_CHANGE_NAME IS '구호물품 대표사진 바뀐 이름';
COMMENT ON COLUMN GOODS.GOODS_HITS IS '구호물품 조회수';


-- 7. 구호물품 구매 목록
CREATE TABLE GOODS_PURCHASE	(
    PURCHASE_NO NUMBER  NOT NULL,
    USER_ID VARCHAR2 NOT NULL,
    GOODS_NO NUMBER NOT NULL,
    BENEFICIARY_NO VARCHAR2(100) NOT NULL, 
    PURCHASE_AMOUNT NUMBER NOT NULL,
    PURCHASE_PRICE NUMBER NOT NULL,
    PURCHASE_DATE DATE DEFAULT SYSDATE NOT NULL,
    PUCHASE_MEANS NUMBER NOT NULL,
    CONSTRAINT FK_GOODS_USER_ID FOREIGN KEY(USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_GOODS_NO FOREIGN KEY(GOODS_NO) REFERENCES GOODS(GOODS_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BENEFICIARY_NO FOREIGN KEY(BENEFICIARY_NO) REFERENCES BENEFICIARY(BE_NO) ON DELETE CASCADE,
    CONSTRAINT FK_PUCHASE_MEANS FOREIGN KEY(PUCHASE_MEANS) REFERENCES PAYMENT(PAY_NO) ON DELETE CASCADE,
    CONSTRAINT PK_GOODS PRIMARY KEY(PURCHASE_NO,USER_ID)
);		

COMMENT ON TABLE GOODS_PURCHASE IS '구호물품구매목록';
COMMENT ON COLUMN GOODS_PURCHASE.PURCHASE_NO IS '구매 목록 번호';
COMMENT ON COLUMN GOODS_PURCHASE.USER_ID IS '유저 ID';
COMMENT ON COLUMN GOODS_PURCHASE.GOODS_NO IS '구호물품 번호';
COMMENT ON COLUMN GOODS_PURCHASE.BENEFICIARY_NO IS '후원처 번호';
COMMENT ON COLUMN GOODS_PURCHASE.PURCHASE_AMOUNT IS '개수';
COMMENT ON COLUMN GOODS_PURCHASE.PURCHASE_PRICE IS '가격';
COMMENT ON COLUMN GOODS_PURCHASE.PURCHASE_DATE IS '구매 날짜';
COMMENT ON COLUMN GOODS_PURCHASE.PUCHASE_MEANS IS '결제 수단';





-- 17_후원처 필요 물품 카테고리	
CREATE TABLE REQUIRED_CATEGORY(
    GOODS_CATEGORY_NO NUMBER NOT NULL,
    BENEFICIARY_NO NUMBER NOT NULL,
    CONSTRAINT FK_REQUIRD_GOODS_CATEGORY_NO FOREIGN KEY(GOODS_CATEGORY) REFERENCES GOODS_CATEGORY(GOODS_CATEGORY_NO) ON DELETE CASCADE,
    CONSTRAINT FK_REQUIRED_BENEFICIARY_NO FOREIGN KEY(BENEFICIARY_NO) REFERENCES BENEFICIARY(BENEFICIARY_NO) ON DELETE CASCADE,
    CONSTRAINT PK_GOODS PRIMARY KEY(GOODS_CATEGORY_NO,BENEFICIARY_NO)
);
COMMENT ON TABLE REQUIRED_CATEGORY IS '후원처 필요 물품 카테고리';
COMMENT ON COLUMN REQUIRED_CATEGORY.GOODS_CATEGORY_NO IS '물품 카테고리';
COMMENT ON COLUMN REQUIRED_CATEGORY.BENEFICIARY_NO IS '후원처번호';

-- 구호물품 첨부파일
CREATE TABLE GOODS_IMAGE(
    GOODS_NO NUMBER NOT NULL,
    IMG_NO NUMBER NOT NULL,
    IMG_ORIGIN_NAME VARCHAR2(1000) NOT NULL,
    IMG_CHANGE_NAME VARCHAR2(1000) NOT NULL,
    CONSTRAINT FK_IMAGE_GOODS_NO FOREIGN KEY(GOODS_NO) REFERENCES GOODS(GOODS_NO) ON DELETE CASCADE,
    CONSTRAINT PK_IMAGE_GOODS_NO PRIMARY KEY(IMG_NO)
);
COMMENT ON TABLE FUNDING_IMAGE IS '펀딩프로젝트_첨부파일';
COMMENT ON COLUMN FUNDING_IMAGE.FP_NO IS '펀딩프로젝트 게시글 번호';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_NO IS '첨부파일 번호';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_ORIGIN_NAME IS '이미지 변경된 이름';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_CHANGE_NAME IS '이미지 기존 이름';



-- 펀딩프로젝트 
CREATE TABLE FUNDING_PROJECT (
    FP_NO NUMBER,
    FP_NAME VARCHAR2(100) NOT NULL,
    HOST_NAME VARCHAR2(50) NOT NULL,
    GOAL_PRICE NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    CLOSING_DATE DATE NOT NULL,
    CONTENTS VARCHAR2(1000) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    CATEGORY_NO NUMBER  NOT NULL,
    HITS NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y',
    THUMBNAIL_ORIGIN_NAME VARCHAR2(1000),
    THUMBNAIL_CHANGE_NAME VARCHAR2(1000),
    FP_WRITE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_FP_CATEGORY_NO FOREIGN KEY(CATEGORY_NO) REFERENCES FUNDING_CATEGORY(FUNDING_CATEGORY_NO) ON DELETE CASCADE,
    CONSTRAINT PK_FUNDING_PROJECT PRIMARY KEY(FP_NO)
);
COMMENT ON TABLE FUNDING_PROJECT IS '펀딩 프로젝트';
COMMENT ON COLUMN FUNDING_PROJECT.FP_NO IS '프로젝트 번호';
COMMENT ON COLUMN FUNDING_PROJECT.FP_NAME IS '프로젝트 명';
COMMENT ON COLUMN FUNDING_PROJECT.HOST_NAME IS '프로젝트 주최자';
COMMENT ON COLUMN FUNDING_PROJECT.GOAL_PRICE IS '목표 금액';
COMMENT ON COLUMN FUNDING_PROJECT.START_DATE IS '프로젝트 시작일';
COMMENT ON COLUMN FUNDING_PROJECT.CLOSING_DATE IS '프로젝트 마감일';
COMMENT ON COLUMN FUNDING_PROJECT.CONTENTS IS '프로젝트 내용';
COMMENT ON COLUMN FUNDING_PROJECT.PAYMENT_DATE IS '프로젝트 결제 예정 일자';
COMMENT ON COLUMN FUNDING_PROJECT.CATEGORY_NO IS '펀딩프로젝트 카테고리 번호';
COMMENT ON COLUMN FUNDING_PROJECT.HITS IS '프로젝트 조회수';
COMMENT ON COLUMN FUNDING_PROJECT.STATUS IS '상태';
COMMENT ON COLUMN FUNDING_PROJECT.THUMBNAIL_ORIGIN_NAME IS '프로젝트 대표이미지 기존 이름';
COMMENT ON COLUMN FUNDING_PROJECT.THUMBNAIL_CHANGE_NAME IS '프로젝트 대표이미지 바뀐 이름';

-- 펀딩 프로젝트 펀딩 품목
CREATE TABLE FUNDIONG_GOODS(
    FP_NO NUMBER NOT NULL,
    FG_NO NUMBER NOT NULL,
    FG_NAME VARCHAR2(500) NOT NULL,
    FG_CONTENT VARCHAR2(2000)  NOT NULL,
    FG_PRICE NUMBER NOT NULL,
    CONSTRAINT FK_FUNDIONG_GOODS_NO FOREIGN KEY(FP_NO) REFERENCES FUNDING_PROJECT(FP_NO) ON DELETE CASCADE,
    CONSTRAINT PK_FUNDIONG_GOODS_NO PRIMARY KEY(FP_NO,FG_NO)
);
COMMENT ON TABLE FUNDIONG_GOODS IS '펀딩 프로젝트 펀딩 품목';
COMMENT ON COLUMN FUNDIONG_GOODS.FP_NO IS '프로젝트 번호';
COMMENT ON COLUMN FUNDIONG_GOODS.FG_NO IS '펀딩 품목 번호';
COMMENT ON COLUMN FUNDIONG_GOODS.FG_NAME IS '펀딩 품목 이름';
COMMENT ON COLUMN FUNDIONG_GOODS.FG_CONTENT IS '펀딩 품목 내용';
COMMENT ON COLUMN FUNDIONG_GOODS.FG_PRICE IS '펀딩 품목 가격';

-- 펀딩 후원자 목록
CREATE TABLE FUNDIONG_SUPPORTER	(
    FS_NO NUMBER NOT NULL,
    FP_NO NUMBER NOT NULL,
    FP_SUPPORTER VARCHAR2 NOT NULL,
    FP_SUPPORT_DATE DATE NOT NULL ,
    FP_PRICE NUMBER  NOT NULL,
    FG_NO NUMBER  NOT NULL,
    TAKE_NAME VARCHAR2(20),
    TAKE_ADDRESS VARCHAR2(300),
    TAKE_PHONE VARCHAR2(30),
    TAKE_POSTCODE NUMBER,
    PAY_NO NUMBER NOT NULL,
    CONSTRAINT FK_FUNDIONG_FG_NO FOREIGN KEY(FG_NO) REFERENCES FUNDIONG_GOODS(FG_NO) ON DELETE CASCADE,
    CONSTRAINT FK_FUNDIONG_SUPPORTER FOREIGN KEY(FP_SUPPORTER) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FUNDIONG_ FOREIGN KEY(PAY_NO) REFERENCES PAYMENT(PAY_NO) ON DELETE CASCADE,
    CONSTRAINT PK_FS_NO PRIMARY KEY(FS_NO)
);
COMMENT ON TABLE FUNDIONG_SUPPORTER IS '펀딩 후원자 목록';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FS_NO IS '펀딩후원 번호';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FP_NO IS '펀딩 프로젝트 번호';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FP_SUPPORTER IS '펀딩 후원자';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FP_SUPPORT_DATE IS '펀딩 후원 일자';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FP_PRICE IS '후원 금액';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.FG_NO IS '펀딩 품목 번호';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.TAKE_NAME IS '받는이 이름';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.TAKE_ADDRESS IS '받는이 주소';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.TAKE_PHONE IS '받는이 전화번호';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.TAKE_POSTCODE IS '받는이 우편번호';
COMMENT ON COLUMN FUNDIONG_SUPPORTER.PAY_NO IS '결제 수단 번호';

-- 펀딩프로젝트 첨부파일
CREATE TABLE FUNDING_IMAGE(
    FP_NO NUMBER NOT NULL,
    IMG_NO NUMBER NOT NULL,
    IMG_ORIGIN_NAME VARCHAR2(1000) NOT NULL,
    IMG_CHANGE_NAME VARCHAR2(1000) NOT NULL,
    CONSTRAINT FK_IMAGE_FP_NO FOREIGN KEY(FP_NO) REFERENCES FUNDING_PROJECT(FP_NO) ON DELETE CASCADE,
    CONSTRAINT PK_IMG_NO PRIMARY KEY(IMG_NO)
);
COMMENT ON TABLE FUNDING_IMAGE IS '펀딩프로젝트_첨부파일';
COMMENT ON COLUMN FUNDING_IMAGE.FP_NO IS '펀딩프로젝트 게시글 번호';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_NO IS '첨부파일 번호';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_ORIGIN_NAME IS '이미지 변경된 이름';
COMMENT ON COLUMN FUNDING_IMAGE.IMG_CHANGE_NAME IS '이미지 기존 이름';


-- 펀딩 프로젝트 댓글
CREATE TABLE FUNDING_REPLY(
    REPLY_NO NUMBER,
    REPLY_WRITER VARCHAR2(30),
    REF_FUNDING_NO NUMBER,
    CREATE_DATE DATE,
    REPLY_CONTENTS VARCHAR2(1000),
    CONSTRAINT FK_REF_BNO FOREIGN KEY(REF_BNO) REFERENCES FUNDING_PROJECT(FP_NO) ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_WRITER FOREIGN KEY(REPLY_WRITER) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT PK_FP_REPLY_NO PRIMARY KEY(REPLY_NO)
);
COMMENT ON TABLE  FUNDING_REPLY IS '펀딩 프로젝트 댓글';
COMMENT ON COLUMN FUNDING_REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN FUNDING_REPLY.REPLY_WRITER IS '작성자';
COMMENT ON COLUMN FUNDING_REPLY.REF_BNO IS '게시글 번호';
COMMENT ON COLUMN FUNDING_REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN FUNDING_REPLY.REPLY_CONTENTS IS '댓글 내용';



-- ============================= SEQUENCE ======================================== 
-- 펀딩프로젝트 게시글 번호
CREATE SEQUENCE SEQ_FUNDING_PROJECT
INCREMENT BY 1
START WITH 1
CACHE 20;

-- 구호물품 게시글 번호
CREATE SEQUENCE SEQ_GOODS
INCREMENT BY 1
START WITH 1
CACHE 20;

-- 펀딩프로젝트 카테고리 번호
CREATE SEQUENCE FUNDING_CATEGORY
INCREMENT BY 1
START WITH 1
CACHE 20;

-- 구호물품 카테고리 번호
CREATE SEQUENCE GOODS_CATEGORY
INCREMENT BY 1
START WITH 1
CACHE 20;


-- ============================= TRRIGER ======================================== 



-- ============================= VIEW ======================================== 


COMMIT;