
SELECT ROWNUM, ASK_NO, F_TYPENAME, ASK_TITLE, USER_NAME, ASK_DATE, ASK_STATUS, ASK_CONTENT,ANSWERED
		FROM ASK
        JOIN MEMBER ON ASK_ID=USER_ID
		JOIN FAQ_TYPE ON ASK_TYPENUM=F_TYPENO	

/************************************************************************/
ALTER TABLE ASK MODIFY ASK_DATE DATE DEFAULT SYSDATE;
ALTER TABLE ASK DROP(ASK_EMAIL);
ALTER TABLE ASK DROP(ASK_PHONE);



--1
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'이중 결제가 되었는데 취소가 가능한가요?','제곧내',NULL,NULL,'user01',NULL,2,DEFAULT,'N');

--2
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'후원처 등록은 어떻게 하나요?','제곧내',NULL,NULL,'user01',NULL,3,DEFAULT,'N');

--3
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'문의드립니다 문의드립니다','제곧내',NULL,NULL,'user01',NULL,2,DEFAULT,'N');

--5
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'영자야 일 안하냐','사이트가 이모양 이꼴인데 일 안하냐',NULL,NULL,'user01','썅놈아 개열심히하는 중인데 개새끼야',2,DEFAULT,'Y');

--6
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'아오','아오 열받아서 못쓰겠네!',NULL,NULL,'user01',NULL,2,DEFAULT,'N');

--7
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'엄마카드로 후원했는데 엄마가 환불해오래요','제곧내',NULL,NULL,'user02',NULL,2,DEFAULT,'N');

--8
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'사이트 개선방안 건의!','이건희',NULL,NULL,'user02',NULL,2,DEFAULT,'N');

--9
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'박춘삼.8학년2반.입니다.','제곧내',NULL,NULL,'user02',NULL,2,DEFAULT,'N');

--10
INSERT INTO ASK VALUES(SEQ_ASK.NEXTVAL,'비즈니스 문의는 어디로 드리면 될까요?','제곧내',NULL,NULL,'user02',NULL,2,DEFAULT,'N');

