INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, 'KB국민은행 ');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '우리은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, 'KEB하나은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '신한은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '대구은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '부산은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '경남은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '광주은행');


INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '제주은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '전북은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '케이뱅크');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '카카오뱅크');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, 'KDB산업은행 ');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, 'IBK기업은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '수협은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, 'NH농협은행');

INSERT INTO BANK VALUES(SEQ_BANK.NEXTVAL, '우정사업본부');


/*
PAY_NO	NUMBER	No		1	결제번호
USER_ID	VARCHAR2(30 BYTE)	No		2	아이디
CARD_NO	VARCHAR2(100 BYTE)	Yes		3	카드번호
PAY_CVC	NUMBER	Yes		4	CVC번호
PAY_EXPIRY	NUMBER	Yes		5	카드 유효기간
PAY_ACCOUNT	VARCHAR2(100 BYTE)	Yes		6	계좌번호
PAY_NAME	VARCHAR2(30 BYTE)	No		7	예금주
B_NO	NUMBER	No		8	은행번호
*/

--결제 
ALTER TABLE PAYMENT DROP(PAY_ACCOUNT);



