DROP TABLE MEMBER;
DROP TABLE ATTENDANCE;
DROP TABLE SUPPORT_COMMENT;
DROP TABLE REVIEW_COMMENT;

DROP SEQUENCE SEQ_ATT;
DROP SEQUENCE SEQ_SPC;
DROP SEQUENCE SEQ_REC;


--------------------------------------------------
--------------     MEMBER 테이블	   ---------------
--------------------------------------------------
 -- A는 개인, B는 단체, C는 기업으로 구분한다.
 
CREATE TABLE MEMBER(
	USER_ID VARCHAR2(30) PRIMARY KEY,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	USER_NICK VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100)  NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PHONE VARCHAR2(13) UNIQUE NOT NULL,
	BIRTHDATE DATE NOT NULL,
	USER_ROLE VARCHAR2(1) DEFAULT 'A' CHECK(USER_ROLE IN('A', 'B', 'C')),
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    USER_CREATE_DATE DATE DEFAULT SYSDATE,
    POINT NUMBER
);

COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.USER_NICK IS '닉네임';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.BIRTHDATE IS '생년월일';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '역할';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태';
COMMENT ON COLUMN MEMBER.USER_CREATE_DATE IS '계정생성일';
COMMENT ON COLUMN MEMBER.POINT IS '총포인트';


INSERT INTO MEMBER 
VALUES ('admin', '1234', '관리자', '컨트롤타워', '서울시 강남구 역삼동', 'admin@donet.com', '010-0000-0000', '1989-12-23', DEFAULT, DEFAULT, SYSDATE, 0);
INSERT INTO MEMBER 
VALUES ('user01', 'pass01', '유저1', '첫회원', '서울시 강남구 역삼동', 'user01@donet.com', '010-1111-1111', '1990-11-21', DEFAULT, DEFAULT, SYSDATE, 0);
INSERT INTO MEMBER 
VALUES ('user02', 'pass02', '유저2', '두번째회원', '서울시 강남구 역삼동', 'user02@donet.com', '010-2222-2222', '1995-12-25', DEFAULT, DEFAULT, SYSDATE, 0);

--------------------------------------------------
-----------     ATTENDANCE 테이블	   -----------
--------------------------------------------------

CREATE TABLE ATTENDANCE(
    ATT_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    ATT_POINT NUMBER,
    ATT_POPUP VARCHAR2(200) NOT NULL,
    ATT_CONTINUITY NUMBER,
    ATT_DATE DATE DEFAULT SYSDATE,
    ATT_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP - INTERVAL '1' minute,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID)
);

CREATE SEQUENCE SEQ_ATT NOCACHE;

COMMENT ON COLUMN ATTENDANCE.ATT_ID IS '출석ID번호';
COMMENT ON COLUMN ATTENDANCE.USER_ID IS '아이디';
COMMENT ON COLUMN ATTENDANCE.ATT_POINT IS '출석포인트';
COMMENT ON COLUMN ATTENDANCE.ATT_POPUP IS '출석팝업';
COMMENT ON COLUMN ATTENDANCE.ATT_CONTINUITY IS '연속출석일수';
COMMENT ON COLUMN ATTENDANCE.ATT_DATE IS '출석날짜';
COMMENT ON COLUMN ATTENDANCE.ATT_DATETIME IS '출석시간';

INSERT INTO ATTENDANCE 
VALUES (SEQ_ATT.NEXTVAL, 'admin', '1000', '출석하였습니다.', '1', SYSDATE, SYSDATE);


------------------------------------------------------------------
--------------     SUPPORT_COMMENT 테이블	   -------------------
------------------------------------------------------------------

CREATE TABLE SUPPORT_COMMENT (
    SP_NO NUMBER PRIMARY KEY,
    SP_CONTENT VARCHAR2(400),
    SP_BNO NUMBER,
    SP_WRITER VARCHAR2(255) NOT NULL,
    SP_CREATE_DATE DATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    FOREIGN KEY (SP_BNO) REFERENCES SUPPORT,
    FOREIGN KEY (SP_WRITER) REFERENCES MEMBER
)

CREATE SEQUENCE SEQ_SPC NOCACHE;

INSERT INTO SUPPORT_COMMENT
VALUES(SEQ_SPC.NEXTVAL, '첫번째 댓글입니다.', 1, 'user01', '20191225',  DEFAULT);
INSERT INTO SUPPORT_COMMENT
VALUES(SEQ_SPC.NEXTVAL, '두번째 댓글입니다.', 1, 'user02', '20191225',  DEFAULT);
INSERT INTO SUPPORT_COMMENT
VALUES(SEQ_SPC.NEXTVAL, '세번째 댓글입니다.', 1, 'user01', '20191225',  DEFAULT);

COMMENT ON COLUMN SUPPORT_COMMENT.SP_NO IS '후원프젝 댓글번호';
COMMENT ON COLUMN SUPPORT_COMMENT.SP_CONTENT IS '후원프젝 댓글내용';
COMMENT ON COLUMN SUPPORT_COMMENT.SP_BNO IS '게시글 번호';
COMMENT ON COLUMN SUPPORT_COMMENT.SP_WRITER IS '작성자';
COMMENT ON COLUMN SUPPORT_COMMENT.SP_CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN SUPPORT_COMMENT.STATUS IS '댓글 상태';

------------------------------------------------------------------
--------------     REVIEW_COMMENT 테이블	   -----------------------
------------------------------------------------------------------

CREATE TABLE REVIEW_COMMENT (
    RE_NO NUMBER PRIMARY KEY,
    RE_CONTENT VARCHAR2(400),
    RE_BNO NUMBER,
    RE_WRITER VARCHAR2(255) NOT NULL,
    RE_CREATE_DATE DATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    FOREIGN KEY (RE_BNO) REFERENCES REVIEW,
    FOREIGN KEY (RE_WRITER) REFERENCES MEMBER
)

CREATE SEQUENCE SEQ_REC NOCACHE;

INSERT INTO REVIEW_COMMENT
VALUES(SEQ_REC.NEXTVAL, '첫번째 댓글입니다.', 1, 'user01', '20191225',  DEFAULT);
INSERT INTO REVIEW_COMMENT
VALUES(SEQ_REC.NEXTVAL, '두번째 댓글입니다.', 1, 'user02', '20191225',  DEFAULT);
INSERT INTO REVIEW_COMMENT
VALUES(SEQ_REC.NEXTVAL, '세번째 댓글입니다.', 1, 'user01', '20191225',  DEFAULT);

COMMENT ON COLUMN REVIEW_COMMENT.RE_NO IS '후원후기 댓글번호';
COMMENT ON COLUMN REVIEW_COMMENT.RE_CONTENT IS '후원후기 댓글내용';
COMMENT ON COLUMN REVIEW_COMMENT.RE_BNO IS '게시글 번호';
COMMENT ON COLUMN REVIEW_COMMENT.RE_WRITER IS '작성자';
COMMENT ON COLUMN REVIEW_COMMENT.RE_CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REVIEW_COMMENT.STATUS IS '댓글 상태';